import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./provider";
import "./globals.css";
import Navbar from "./components/elements/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    
   <body className="h-screen flex flex-col overflow-hidden">
  <Providers>
    <Navbar />                         {/* shrink-0, natural height */}
    <div className="flex-1 overflow-hidden">
      {children}                       {/* MentorLayout renders here */}
    </div>
  </Providers>
</body>
    </html>
  );
}
